name: simple_dating_app
description: A simplified Tinder-like dating app in Flutter.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1
  firebase_messaging: ^14.4.1
  provider: ^6.0.5
  image_picker: ^0.8.7+5
  flutter_card_swiper: ^4.1.1
  google_sign_in: ^6.1.0
  cached_network_image: ^3.2.3
  uuid: ^3.0.7
  intl: ^0.18.1
  geolocator: ^9.0.1
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
